
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE IF NOT EXISTS EMPLOYEE 
(
	ID serial, 
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	ROLE VARCHAR(50),
	SALARAY NUMERIC(10,2)
);

INSERT INTO EMPLOYEE (FIRST_NAME,LAST_NAME,ROLE,SALARAY)
VALUES ('Jack', 'Jackson', 'Dev I', 100000);

SELECT *
FROM EMPLOYEE;